### ISSUE TITLE
Licanse

### ISSUE THREAD

**Issue by ClearlyElevated** [BotsForDiscord/Beta#1]
Your licanse is meaningless and by no way shape or form covers you with anything. Wants you edit it beyond your name it is invalid.,

**Comment by Habchy** [comment]
False.

A GitHub repository created with no license is automatically All Rights Reserved.
The current license in the repository is just an extension of that.

**Comment by DonovanDMC** [comment]
"Licanse"
"Wants you edit it"
I won't be taking any advice, let alone license advice from that.

**Comment by ClearlyElevated** [comment]
lmao oooh no dont point out a typo. are you in 7th fucking grade lol get real show me a website that says it is valid after being edited. I actually have a few registered copyrights & TM in my name. So before going around thinking a doc u tweaked with online that says license has any legal binding it sound like you shouldn't take advice from yourself or have yet to drop a popular enough project to experience the need for acting upon it..

**Comment by Habchy** [comment]
Meme.

**Comment by DonovanDMC** [comment]
You can start talking legal advice, once again, after you go back to third grade and learn some grammar.

**Comment by Clemens-E** [comment]
My dad owns copyright, he will ban you!
BTW you make weird typos, because you wrote it twice 😃

**Comment by DonovanDMC** [comment]
kek
